//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Clinics = new HashSet<Clinic>();
        }
    
        public int DoctorId { get; set; }
        public Nullable<int> FormNumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Title { get; set; }
        public string FullName { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string MobileNumber { get; set; }
        public string LandLineNumber { get; set; }
        public string Qualifications { get; set; }
        public string Speciality { get; set; }
        public string Expertise { get; set; }
        public string RegistrationNumber { get; set; }
        public string YearsOfExperience { get; set; }
        public string ShortProfile { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<bool> Subscription { get; set; }
        public Nullable<bool> SmartPhone { get; set; }
    
        public virtual ICollection<Clinic> Clinics { get; set; }
    }
}
