//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yogacenter
    {
        public int ProcessingNumberId { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public bool Gender { get; set; }
        public string Nationality { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PermanantAddress { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime Date { get; set; }
        public string Email { get; set; }
        public string AcademicQualification { get; set; }
        public int Course { get; set; }
        public int HealthStatus { get; set; }
    }
}
