//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorsManagmentSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clinic
    {
        public int DoctorId { get; set; }
        public string ClinicName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public bool ReceptionistAvaliable { get; set; }
        public Nullable<bool> LoginNeededForReceptionist { get; set; }
        public string ReceptionistLoginMobileNumber { get; set; }
        public string LandlineNumberOrMobileNumber { get; set; }
        public string EmailId { get; set; }
        public System.TimeSpan MorningStartTime { get; set; }
        public System.TimeSpan MorningEndTime { get; set; }
        public System.TimeSpan EveningStartTime { get; set; }
        public System.TimeSpan EveningEndTime { get; set; }
        public string Holidays { get; set; }
        public Nullable<System.DateTime> ScheduleDeatils { get; set; }
        public bool AppointmentMode { get; set; }
        public Nullable<bool> AppointmentSlotTime { get; set; }
        public string AdditionalServicesInClinic { get; set; }
        public string Fees { get; set; }
        public string FollowUp { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
